version: "2"

services:

  uwsgi:
    build:
        context:    .
        dockerfile: uwsgi.dockerfile
    container_name: uwsgi-server
    restart:        unless-stopped
    networks:
      - nginx-network
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes:/var/uwsgi:rw
      
networks:
    nginx-network:
        external: true
