version: "2"

services:

  postfix-server:
    image:          catatnight/postfix:latest
    container_name: postfix-server
    restart:        unless-stopped
    ports:
      - "25:25"
    networks:
      - postfix-network
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - maildomain=mail.radiopochard.com
      - smtp_user=postfixuser:postfixuser_password

networks:
    postfix-network:
        external:   true
