version: "2"

services:

  web:
    image: nginx
    container_name: nginx-server
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"    
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/log:/var/log/nginx:rw
      - ./volumes/configuration/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./volumes/configuration/sites:/etc/nginx/sites:ro
      - ./volumes/data/html:/usr/share/nginx/html:ro
      - ./volumes/data/certbot:/var/certbot:rw
      # TODO : supprimer ça :
      - /var/radiopochard:/var/radiopochard:ro
      # TODO : path to sites     		- /usr/share/sites:/usr/share/sites:ro
      # TODO : path to certificates		- /toto/tata/cert:/cert:ro
