version: "2"

services:

  web:
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"    
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/web/cert:/cert:ro
      - ./volumes/configuration/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./volumes/configuration/sites:/etc/nginx/sites:ro
      # Contains dummy HTML files
      - /var/www/radiopochard:/usr/share/nginx/html:ro
