version: "2"

services:

  nginx-server:
    image:          nginx:1.13.3
    container_name: nginx-server
    restart:        unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx-network
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/nginx/cert:ro
      - ./volumes/log:/var/log/nginx:rw
      - ./volumes/configuration/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./volumes/configuration/sites:/etc/nginx/sites:ro
      - ./volumes/data/html:/usr/share/nginx/html:ro
      - ./volumes/data/certbot:/var/certbot:rw

networks:
    nginx-network:
        external:   true
