version: "2"

services:

  db:
    image:          postgres:9.4
    container_name: <NOM_DU_SITE>-mattermost-db
    restart:        unless-stopped
    networks:
      - <NOM_DU_SITE>-mattermost-network
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/broccoli/<NOM_DU_SITE>/mattermost/db/var/lib/postgresql/data:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost

  app:
    image:          mattermost/mattermost-prod-app:4.1.0
    container_name: <NOM_DU_SITE>-mattermost-app
    restart:        unless-stopped
    networks:
      - nginx-network
      - <NOM_DU_SITE>-mattermost-network
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/broccoli/<NOM_DU_SITE>/mattermost/app/mattermost/config:/mattermost/config:rw
      - /var/broccoli/<NOM_DU_SITE>/mattermost/app/mattermost/data:/mattermost/data:rw
      - /var/broccoli/<NOM_DU_SITE>/mattermost/app/mattermost/logs:/mattermost/logs:rw
    environment:
      - DB_HOST=<NOM_DU_SITE>-mattermost-db
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmuser_password
      - MM_DBNAME=mattermost
      
networks:
    nginx-network:
        external: true
    <NOM_DU_SITE>-mattermost-network:
        external: true
    